/* This is the Entry Point of the website, "the main file."
** Here we generate the "root," the HTML element where our React hierarchy will be rendered/mounted from.
** Conveniently we also set some global CSS rules to apply to all of our components, and set up our Routing to link
** each webpage. */

import ReactDOM from 'react-dom'
import { BrowserRouter, Routes, Route } from "react-router-dom"

import Home from './Pages/Home/Components/home'
import About from './Pages/About/Components/about'
import Events from './Pages/Events/Components/events'
import Links from './Pages/Links/Components/links'
import Leadership from './Pages/Leadership/Components/leadership'
import Archives from './Pages/Archives/Components/archives'
import LeadershipBio from './Pages/Leadership/Components/leadershipBio'

/* Set the browser tab title, also for SEO (so when Google queries searches for 'OYFA' this is what it finds) */
document.title = "OYFA at UVA"

/* Tell the React Document Object Model to create a root HTML element for us */
const root = ReactDOM.createRoot(document.getElementById('root'));

/* Apply some global CSS rules to apply to every page */
const globalStyles = `
    body {
      overflow-x: hidden; /* Hide horizontal scrollbar */
    }`

/* If adding new pages, add a new route with a relative link pointing to the new page and 
** set the element to the main class of your page 
**
** In general, use React <Link> instead of anchor <a href=''> for navigating between pages (for external websites is ok)
** <a> triggers a refresh which can possibly reset any data we are potentially passing between pages */

/* Our root is now pathed to all of our pages */

root.render(
  <>
    <style>{globalStyles}</style>

    <BrowserRouter>
      <Routes>
          <Route path='/' element={<Home />} />
          <Route path='/About' element={<About />} />
          <Route path='/Events' element={<Events />} />
          <Route path='/Links' element={<Links />} />
          <Route path='/Leadership' element={<Leadership />} />
          <Route path='/Archives' element={<Archives />} />
          <Route path='/Bios' element={<LeadershipBio />} /> {/*Bios is not on the Navbar but is linked on Leadership page*/}
      </Routes>
    </BrowserRouter>
  </>
)

// NOTE: AUTOGENERATED TEXT:
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
//reportWebVitals();