/* This is the Entry Point of the website, "the main file."
** Here we generate the "root," the HTML element where our React hierarchy will be rendered/mounted from.
** Conveniently we also set some global CSS rules to apply to all of our components, and set up our Routing to link
** each webpage. */

import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'

/* Set the browser tab title, also for SEO (so when Google queries searches for 'OYFA' this is what it finds) */
document.title = "OYFA at UVA"

/* Tell the React Document Object Model to create a root HTML element for us */
const root = ReactDOM.createRoot(document.getElementById('root'));

/* Our root is now pathed to all of our pages */

root.render(
  <>
      <React.StrictMode>
        <App/>
      </React.StrictMode>
  </>
)

// NOTE: AUTOGENERATED TEXT:
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
//reportWebVitals();